server:
  port: 6868
spring:
  application:
    name: tensquare-eureka
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://192.168.109.128:${server.port}/eureka/
